language: node_js
sudo: required  # See http://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
node_js:
  - "10.10.0"
script:
  - node_modules/gulp/bin/gulp.js test
cache:
  yarn: true
  directories:
  - node_modules
group: deprecated # https://github.com/travis-ci/travis-ci/issues/6928
